# Intro to Numpy

In [4]:
import numpy as np


In [5]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.full(10, 8)

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [14]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [16]:
# access an element of the array
a[2] = 9

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [25]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [23]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [26]:
# multidimensional arrays

In [30]:
n = np.zeros((5,2))

In [34]:
n[0,1] = 20
n

array([[ 0., 20.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [45]:
#access rows
n[1] = [4,8]
n

array([[ 0., 20.],
       [ 4.,  8.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [51]:
#access columns
n[:,0]

array([0., 4., 0., 0., 0.])

In [53]:
# random package - values b/n 0 and 1 (pseudo-random)
np.random.rand(5,2)

array([[0.86141474, 0.0108962 ],
       [0.91249649, 0.40537432],
       [0.66797292, 0.54863927],
       [0.52576287, 0.66679295],
       [0.27315382, 0.26513973]])

In [64]:
np.random.seed(0)
np.random.randn(5,2)
# seed -  return same random values
# randn - normalized values

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ]])

In [68]:
np.random.seed(0)
np.random.randint(low= 0,high = 100, size = (5,2))

array([[44, 47],
       [64, 67],
       [67,  9],
       [83, 21],
       [36, 87]])

In [76]:
# Element wise operations
k = np.arange(5)
k

array([0, 1, 2, 3, 4])

In [77]:
b = k * 5
b

array([ 0,  5, 10, 15, 20])

In [86]:
c = k + b
c

array([ 0,  6, 12, 18, 24])

In [83]:
# comparison operator
c >= 17

array([False, False, False,  True,  True])

In [85]:
c[c > b]

array([ 6, 12, 18, 24])

In [88]:
# summarizing operations
b

array([ 0,  5, 10, 15, 20])

In [89]:
b.sum()

np.int64(50)

In [92]:
n.sum()

np.float64(32.0)